# Generated by Django 2.0.6 on 2018-06-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='fecha_venta',
            field=models.DateField(verbose_name='Fecha de venta'),
        ),
    ]
