# Generated by Django 2.0.6 on 2018-06-11 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20180611_2244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Venta',
        ),
    ]
