# Generated by Django 2.0.6 on 2018-06-11 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20180611_2248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Venta',
            new_name='Ventas',
        ),
    ]
